### ISSUE TITLE
Leak Sensor Broken

### ISSUE THREAD

**Issue by benroscoe** [TD22057/insteon-mqtt#120]
I recently migrated my docker install and it pulled the latest. I get the following error with a leak sensors. It looks like a recent update was made but something wasn't fully updated in that change

2019-02-18 03:24:23 INFO Modem: Created leak at 2e.13.f5 (leak water heater)
Traceback (most recent call last):
  File "/usr/local/bin/insteon-mqtt", line 5, in <module>
    status = insteon_mqtt.cmd_line.main()
  File "/usr/local/lib/python3.6/site-packages/insteon_mqtt/cmd_line/main.py", line 312, in main
    return args.func(args, cfg)
  File "/usr/local/lib/python3.6/site-packages/insteon_mqtt/cmd_line/start.py", line 48, in start
    config.apply(cfg, mqtt_handler, modem)
  File "/usr/local/lib/python3.6/site-packages/insteon_mqtt/config.py", line 63, in apply
    modem.load_config(config['insteon'])
  File "/usr/local/lib/python3.6/site-packages/insteon_mqtt/Modem.py", line 137, in load_config
    self._load_devices(data.get('devices', []))
  File "/usr/local/lib/python3.6/site-packages/insteon_mqtt/Modem.py", line 774, in _load_devices
    self.signal_new_device.emit(self, dev)
  File "/usr/local/lib/python3.6/site-packages/insteon_mqtt/Signal.py", line 47, in emit
    slot(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/insteon_mqtt/mqtt/Mqtt.py", line 173, in handle_new_device
    obj = mqtt_cls(self, device)
  File "/usr/local/lib/python3.6/site-packages/insteon_mqtt/mqtt/Leak.py", line 40, in __init__
    device.signal_is_wet.connect(self._insteon_is_wet)
AttributeError: 'Leak' object has no attribute 'signal_is_wet'

**Comment by benroscoe** [comment]
Pulled your updated changes into the container and it worked perfectly. Thanks for the super quick response!

**Comment by TD22057** [comment]
No problem - I've been doing some code cleanup and renaming things for consistency and missed that one.
