### ISSUE TITLE
Unable to start Insteon MQTT

### ISSUE THREAD

**Issue by Predator04** [TD22057/insteon-mqtt#149]
kdir: can't create directory '/config/insteon-mqtt/': File exists
Traceback (most recent call last):
  File "/usr/bin/insteon-mqtt", line 5, in <module>
    status = insteon_mqtt.cmd_line.main()
  File "/usr/lib/python3.6/site-packages/insteon_mqtt/cmd_line/main.py", line 306, in main
    cfg = config.load(args.config)
  File "/usr/lib/python3.6/site-packages/insteon_mqtt/config.py", line 47, in load
    return yaml.load(f, Loader)
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.6/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "/config/insteon-mqtt/config.yaml", line 18, column 1
expected <block end>, but found '<block mapping start>'
  in "/config/insteon-mqtt/config.yaml", line 134, column 3

**Comment by TD22057** [comment]
How did you start the app?  What's in the config file?  It says there is in an error in config.yaml - did you look at the file to see what the error is?  The error seems to indicate that you are missing a quote but there is no way anyone can help without a reasonable amount of information.

**Comment by Predator04** [comment]
Started from hassio > Insteon MQTT

Line 18 in config: logging:
  level: 10


Line 134:
  keep_alive: 30

none of that was changed that is all default.
If you need anything else let me know I'm not sure what is needed. Thanks!

**Comment by Predator04** [comment]
Here is config: https://pastebin.com/JkqdsvQj

**Comment by TD22057** [comment]
Those lines not changing is not the error - it's what you changed in between that's the error.  Since the last line is 134, I'm guessing it's an error in your secret inputs.  Try putting them in directly - I don't run hassio but this module doesn't know anything about HASS so I doubt that putting secrets in the file works.  Either that or the secrets being substituted aren't valid yaml.

**Comment by Predator04** [comment]
Ah got it. I will try that and report back

**Comment by Predator04** [comment]
Same thing. Same error: 
config: https://pastebin.com/YcmwaSjx



mkdir: can't create directory '/config/insteon-mqtt/': File exists
Traceback (most recent call last):
  File "/usr/bin/insteon-mqtt", line 5, in <module>
    status = insteon_mqtt.cmd_line.main()
  File "/usr/lib/python3.6/site-packages/insteon_mqtt/cmd_line/main.py", line 306, in main
    cfg = config.load(args.config)
  File "/usr/lib/python3.6/site-packages/insteon_mqtt/config.py", line 47, in load
    return yaml.load(f, Loader)
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.6/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "/config/insteon-mqtt/config.yaml", line 18, column 1
expected <block end>, but found '<block mapping start>'
  in "/config/insteon-mqtt/config.yaml", line 134, column 3

**Comment by Predator04** [comment]
Changed mqtt to :
mqtt:
 broker: core-mosquitto
 username: mosquitto
 password: password

and get this: 
in "/config/insteon-mqtt/config.yaml", line 127, column 2
expected <block end>, but found '<block mapping start>'
  in "/config/insteon-mqtt/config.yaml", line 134, column 3

Which is the mqtt line. That is how its shown to add it. Is that not correct?

**Comment by Predator04** [comment]
Added like this: https://pastebin.com/YEpH1UGA

**Comment by Predator04** [comment]
Added it like this: https://pastebin.com/3QQNgdx2

But it doesn't seem to like it that way even tho that's how its set?

**Comment by Predator04** [comment]
OK I got that error to go away. After formatting it. Now I get this: https://pastebin.com/9Cf8kejk

Sorry for all this but the setup instructions are not updated with everything that is needed.

**Comment by Predator04** [comment]
I got that part working. Working on getting the rest of these errors figured out. Will post back.

**Comment by Predator04** [comment]
This is the error I get now:

https://pastebin.com/xgkh2LAQ

I tried adding the ip adrress and everything. What should be there?

**Comment by Predator04** [comment]
OK got that to work now buy adding a 'username' 'password' around the username and password

**Comment by Predator04** [comment]
2019-05-17 00:13:30 WARNING Protocol: No read handler found for message type 0x6a: All link get next ack: False
2019-05-17 00:13:32 INFO Protocol: Read 0x6a: All link get next ack: False


any idea what this means?

**Comment by TD22057** [comment]
Did you get it working?  There isn't much I can help with - that little snippet of log doesn't tell me enough to know what you're trying to do.

**Comment by TD22057** [comment]
Closing - no reply since July (feel free to reopen).
