### ISSUE TITLE
Not handling humidity report from thermostat

### ISSUE THREAD

**Issue by azteknetworking** [TD22057/insteon-mqtt#160]
It seems to not handle the particular reporting for humidity status updates from this thermostat if I'm reading the below correctly.  This shows up repeatedly in the log whenever the Thermostat reports a new temperature, but the temp gets reported without issue. Thermostat is a 2441TH. 2413 PLM.

```
2019-09-10 11:37:18 INFO Protocol: Read 0x50: Std: 1e.0c.c7->44.86.b7 Type.DIRECT cmd: 6f 28
2019-09-10 11:37:18 ERROR Serial: Serial read error from /dev/ttyUSB0
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/insteon_mqtt/network/Serial.py", line 184, in read_from_link
    self.signal_read.emit(self, data)
  File "/usr/local/lib/python3.7/site-packages/insteon_mqtt/Signal.py", line 47, in emit
    slot(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/insteon_mqtt/Protocol.py", line 325, in _data_read
    self._process_msg(msg)
  File "/usr/local/lib/python3.7/site-packages/insteon_mqtt/Protocol.py", line 428, in _process_msg
    status = handler.msg_received(self, msg)
  File "/usr/local/lib/python3.7/site-packages/insteon_mqtt/handler/ThermostatCmd.py", line 94, in msg_received
    self.device.signal_humid_change.emit(self.device, int(msg.cmd2))
AttributeError: 'Thermostat' object has no attribute 'signal_humid_change'
```

**Comment by gaetanlord** [comment]
Hi

I just complete the initial installation and I also have the same messages in the log.
I have a 2413U PLM and a very old Tstat
T1900 - Venstar Remote Control Thermostat with Humidity with 2441V Insteon Adapter

When I query the device I have the following output.


**Commanding thermostat device 14.61.1a (thermostat) cmd=print_db**
```
14.61.1a (thermostat) device database
DeviceDb: (delta 12)
  0fb7: 4c.14.97 grp: 239 type: CTRL data: 0x03 0x00 0xef
  0fbf: 4c.14.97 grp:   4 type: CTRL data: 0x03 0x00 0x04
  0fc7: 4c.14.97 grp:   3 type: CTRL data: 0x03 0x00 0x03
  0fcf: 4c.14.97 grp:   2 type: CTRL data: 0x03 0x00 0x02
  0fd7: 4c.14.97 grp:   1 type: CTRL data: 0x03 0x00 0x01
  0fdf: 4c.14.97 grp:   1 type: RESP data: 0xff 0x00 0x01
  0fe7: 49.94.be grp: 239 type: CTRL data: 0x01 0x00 0xef
  0fef: 49.94.be grp:   3 type: CTRL data: 0x01 0x00 0x03
  0ff7: 49.94.be grp:   2 type: CTRL data: 0x01 0x00 0x02
  0fff: 49.94.be grp:   1 type: CTRL data: 0x01 0x00 0x01
Unused:
Last:
  0faf: 2b.95.1f grp:   3 type: RESP data: 0xff 0x1f 0x03 (UNUSED) (LAST)
GroupMap
  1 -> ['49.94.be', '4c.14.97']
  2 -> ['49.94.be', '4c.14.97']
  3 -> ['49.94.be', '4c.14.97']
  239 -> ['49.94.be', '4c.14.97']
  4 -> ['4c.14.97']
```

**Commanding thermostat device 14.61.1a (thermostat) cmd=get_model**
```
Device 14.61.1a received model information, dev_cat: 0x5, sub_cat: 0x3, firmware: 0x92 
```

**Comment by gaetanlord** [comment]
Just notice another thread where DEBUG output is requested. I include what I have. So far, seem to be every hours.

```

2019-10-11 17:08:46 INFO Protocol: Read 0x50: Std: 14.61.1a->4c.14.97 Type.DIRECT cmd: 6f 1d
2019-10-11 17:08:46 DEBUG Protocol: Setting next write time: 1570828126.615719
2019-10-11 17:08:46 DEBUG MsgHistory: Received 0 hops, total 0 for 1 entries
2019-10-11 17:08:46 ERROR Serial: Serial read error from /dev/ttyUSB0
Traceback (most recent call last):
  File "/home/insteon/insteon-mqtt/venv/lib/python3.6/site-packages/insteon_mqtt/network/Serial.py", line 184, in read_from_link
    self.signal_read.emit(self, data)
  File "/home/insteon/insteon-mqtt/venv/lib/python3.6/site-packages/insteon_mqtt/Signal.py", line 47, in emit
    slot(*args, **kwargs)
  File "/home/insteon/insteon-mqtt/venv/lib/python3.6/site-packages/insteon_mqtt/Protocol.py", line 325, in _data_read
    self._process_msg(msg)
  File "/home/insteon/insteon-mqtt/venv/lib/python3.6/site-packages/insteon_mqtt/Protocol.py", line 428, in _process_msg
    status = handler.msg_received(self, msg)
  File "/home/insteon/insteon-mqtt/venv/lib/python3.6/site-packages/insteon_mqtt/handler/ThermostatCmd.py", line 94, in msg_received
    self.device.signal_humid_change.emit(self.device, int(msg.cmd2))
AttributeError: 'Thermostat' object has no attribute 'signal_humid_change'
```
