### ISSUE TITLE
device reports readiness to read but returned no data

### ISSUE THREAD

**Issue by house97** [TD22057/insteon-mqtt#165]
Early this afternoon, Insteon-MQTT died, indicating an issue reading from the serial port.  While I'm not saying that's impossible, all I had to do to bring things back to full operation is restart the insteon-mqtt service.  I'm submitting the logs from the incident in case it proves helpful.  The first line below is the last line of the sequence when a light was turned on via hass automation, included to provide context.

`2019-11-17 07:30:00 DEBUG Mqtt: MQTT writing
2019-11-17 13:41:58 ERROR Serial: Serial read error from /dev/ttyUSB0
Traceback (most recent call last):
  File "/opt/insteon-mqtt/lib/python3.6/site-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/insteon-mqtt/lib/python3.6/site-packages/insteon_mqtt/network/Serial.py", line 178, in read_from_link
    data = self.client.read(self.read_buf_size)
  File "/opt/insteon-mqtt/lib/python3.6/site-packages/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2019-11-17 13:41:58 INFO Serial: Serial device closing /dev/ttyUSB0`

The next line in the log was the first line after I restarted the service.

**Comment by house97** [comment]
I believe the cause of this was the USB port mapping on ESXi 6.5 flaking out.  Either that, or the USB extension I had to use to get from the hypervisor to the PLM was causing substantial signal loss, such that intermittently the PLM just disappeared.  I've heard stories of USB extensions causing issues with the PLM.  You'd hope that a 10 ft. cord wouldn't be a huge problem though.
Either way, I'm now running insteon-mqtt on a rPi 3B.  It's running fine, and the beauty of mqtt means it's just as able to interact with home assistant as if it were colocated on.
Closing this issue as unreproducable.
