### ISSUE TITLE
IOLinc for Water Valve and Garage

### ISSUE THREAD

**Issue by pashdown** [TD22057/insteon-mqtt#178]
My two IOLincs appear to be reading sensor status, but setting the scene appears to do nothing.  Do I have these configured wrong?

```
insteon-mqtt/config.yaml:
    # IOLinc relay controllers
    io_linc:
      - 34.88.a7: 'garage'
      - 39.4d.6e: 'water main'

homeassistant/configuration.yaml:
# Insteon IOlinc
- platform: mqtt
  name: "Garage Car Door"
  icon: mdi:garage
  state_topic: insteon/34.88.a7/state
  command_topic: insteon/34.88.a7/scene

 - platform: mqtt
  name: "Water Main"
  icon: mdi:water-pump
  state_topic: insteon/39.4d.6e/state
  command_topic: insteon/39.4d.6e/scene

insteon-mqtt config.yaml get-flags 34.88.a7:
Commanding io_linc device 34.88.a7 (garage) cmd=get_flags
Device 34.88.a7 operating flags: 01001010
Program lock   : 0
Transmit LED   : 1
Relay linked   : 0
Trigger reverse: 1
Relay latching : momentary A
Operation complete

insteon-mqtt config.yaml get-flags 39.4d.6e:
Commanding io_linc device 39.4d.6e (water main) cmd=get_flags
Device 39.4d.6e operating flags: 01000010
Program lock   : 0
Transmit LED   : 1
Relay linked   : 0
Trigger reverse: 1
Relay latching : latching
Operation complete
```

**Comment by TD22057** [comment]
What you posted looks ok, but it's not really enough to tell what's going on.  Please set the logging level to debug and post the log messages that occur when you send the scene command.

**Comment by pashdown** [comment]
Here's me hitting the garage switch first, then the water main.
```
2020-01-17 21:37:35 DEBUG IOLinc: IOLinc message insteon/34.88.a7/scene b'OFF'
2020-01-17 21:37:35 DEBUG MsgTemplate: Input template render: '{ "cmd" : "off" }'
2020-01-17 21:37:35 INFO IOLinc: IOLinc input command: {'cmd': 'off'}
2020-01-17 21:37:35 INFO IOLinc: IOLinc 34.88.a7 (garage) finding correct modem scene to use
2020-01-17 21:37:35 ERROR IOLinc: Can't trigger IOLinc scene - there is no responder from the modem in the IOLinc db
2020-01-17 21:37:46 DEBUG IOLinc: IOLinc message insteon/39.4d.6e/scene b'ON'
2020-01-17 21:37:46 DEBUG MsgTemplate: Input template render: '{ "cmd" : "on" }'
2020-01-17 21:37:46 INFO IOLinc: IOLinc input command: {'cmd': 'on'}
2020-01-17 21:37:46 INFO IOLinc: IOLinc 39.4d.6e (water main) finding correct modem scene to use
2020-01-17 21:37:46 INFO IOLinc: IOLinc 39.4d.6e (water main) found scene 0
2020-01-17 21:37:46 INFO IOLinc: IOLinc 39.4d.6e (water main) triggering modem scene 0
2020-01-17 21:37:46 ERROR IOLinc: Invalid IOLinc scene command: {'cmd': 'on'}
Traceback (most recent call last):
  File "/home/pashdown/insteon-mqtt/venv/lib/python3.7/site-packages/insteon_mqtt/mqtt/IOLinc.py", line 185, in _input_scene
    self.device.scene(is_on)
  File "/home/pashdown/insteon-mqtt/venv/lib/python3.7/site-packages/insteon_mqtt/device/IOLinc.py", line 506, in scene
    self.modem.scene(is_on, self.modem_scene, on_done=on_done)
  File "/home/pashdown/insteon-mqtt/venv/lib/python3.7/site-packages/insteon_mqtt/Modem.py", line 619, in scene
    assert 0x01 <= group <= 0xff
AssertionError
```

**Comment by TD22057** [comment]
Did you run the pair command successfully?  It looks like the virtual scene on the modem was never created.

**Comment by pashdown** [comment]
Pair says the modem db update fails.  Running "refresh modem" does nothing to fix the problem.

```
> insteon-mqtt config.yaml join 39.4d.6e
Commanding io_linc device 39.4d.6e (water main) cmd=join
Device 39.4d.6e engine version: i2c
Operation Complete

> insteon-mqtt config.yaml pair 39.4d.6e
Commanding io_linc device 39.4d.6e (water main) cmd=pair
IOLinc 39.4d.6e (water main) refresh on=False
Device 39.4d.6e db out of date (got 15 vs 13), refreshing
Handler timed out 1 of 3 sent: Ext: 39.4d.6e, Type.DIRECT ext, 2f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Handler timed out 2 of 3 sent: Ext: 39.4d.6e, Type.DIRECT ext, 2f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Entry: 0fcf: 4f.74.36 grp:   1 type: CTRL data: 0x03 0x00 0x00
Entry: 0fc7: 3b.94.af grp:   1 type: RESP data: 0x00 0x00 0x01
Entry: 0fb7: 3b.94.af grp:  37 type: RESP data: 0xff 0x00 0x01
Entry: 0faf: 00.00.00 grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)
39.4d.6e database download complete
DeviceDb: (delta 15)
  0fb7: 3b.94.af grp:  37 type: RESP data: 0xff 0x00 0x01
  0fc7: 3b.94.af grp:   1 type: RESP data: 0x00 0x00 0x01
  0fcf: 4f.74.36 grp:   1 type: CTRL data: 0x03 0x00 0x00
Unused:
Last:
  0faf: 00.00.00 grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)
GroupMap
  1 -> ['4f.74.36']

ERROR: Modem db updated failed: OutAllLinkUpdate: 39.4d.6e grp: 1 Cmd.ADD_RESPONDER ack: False
ERROR: Modem database update failed
Pairing may fail if the modem db is out of date.  Try running
the following and then re-try the pair command.
   insteont-mqtt config.py refresh modem
```

**Comment by pashdown** [comment]
Strike that. I got it to pair by running the pair command immediately after and on the same entry line as "refresh modem".

**Comment by pashdown** [comment]
Debug from Garage open result after pair (nothing happens at IOLinc):
```
2020-01-21 16:09:48 DEBUG IOLinc: IOLinc message insteon/34.88.a7/scene b'OFF'
2020-01-21 16:09:48 DEBUG MsgTemplate: Input template render: '{ "cmd" : "off" }'
2020-01-21 16:09:48 INFO IOLinc: IOLinc input command: {'cmd': 'off'}
2020-01-21 16:09:48 INFO IOLinc: IOLinc 34.88.a7 (garage) triggering modem scene 40
2020-01-21 16:09:48 INFO Modem: Modem scene 40 on=off
2020-01-21 16:09:48 INFO Protocol: Write message to modem: Modem Scene: grp: 40 cmd: 0x13 0x00
2020-01-21 16:09:48 DEBUG Protocol: Write bytes to modem: b'\x02a(\x13\x00'
2020-01-21 16:09:48 DEBUG Serial: Wrote 5 bytes to serial /dev/insteon
2020-01-21 16:09:48 INFO Protocol: Read 0x61: Modem Scene: grp: 40 cmd: 0x13 0x00 ack: True
2020-01-21 16:09:48 DEBUG Protocol: Passing msg to write handler: ModemScene handler
2020-01-21 16:09:49 INFO Protocol: Read 0x58: All link status ack: 1
2020-01-21 16:09:49 DEBUG Protocol: Passing msg to write handler: ModemScene handler
2020-01-21 16:09:49 DEBUG ModemScene: Modem scene 40 command ACK
2020-01-21 16:09:49 DEBUG Modem: Found 1 responders in group 40
2020-01-21 16:09:49 DEBUG Modem: Group 40 -> ['34.88.a7']
2020-01-21 16:09:49 INFO Modem: 3b.94.af (modem) broadcast to 34.88.a7 for group 40
2020-01-21 16:09:49 DEBUG IOLinc: IOLinc 34.88.a7 cmd 0x13
2020-01-21 16:09:49 DEBUG Protocol: Write handler finished
2020-01-21 16:09:49 INFO Protocol: Read 0x50: Std: 34.88.a7 Type.CLEANUP_ACK grp: 28 cmd: 13 28
2020-01-21 16:09:49 DEBUG Protocol: Setting next write time: 1579648189.462373
2020-01-21 16:09:49 DEBUG MsgHistory: Received 1 hops, total 2 for 2 entries
2020-01-21 16:09:49 WARNING Protocol: No read handler found for message type 0x50: Std: 34.88.a7 Type.CLEANUP_ACK grp: 28 cmd: 13 28
```

Debug from Water Main after pair, this actually activated the valve once, then wouldn't turn it back on, but does nothing now:
```
2020-01-21 16:10:25 DEBUG IOLinc: IOLinc message insteon/39.4d.6e/scene b'ON'
2020-01-21 16:10:25 DEBUG MsgTemplate: Input template render: '{ "cmd" : "on" }'
2020-01-21 16:10:25 INFO IOLinc: IOLinc input command: {'cmd': 'on'}
2020-01-21 16:10:25 INFO IOLinc: IOLinc 39.4d.6e (water main) finding correct modem scene to use
2020-01-21 16:10:25 INFO IOLinc: IOLinc 39.4d.6e (water main) found scene 0
2020-01-21 16:10:25 INFO IOLinc: IOLinc 39.4d.6e (water main) triggering modem scene 0
2020-01-21 16:10:25 ERROR IOLinc: Invalid IOLinc scene command: {'cmd': 'on'}
Traceback (most recent call last):
  File "/home/pashdown/insteon-mqtt/venv/lib/python3.6/site-packages/insteon_mqtt/mqtt/IOLinc.py", line 185, in _input_scene
    self.device.scene(is_on)
  File "/home/pashdown/insteon-mqtt/venv/lib/python3.6/site-packages/insteon_mqtt/device/IOLinc.py", line 506, in scene
    self.modem.scene(is_on, self.modem_scene, on_done=on_done)
  File "/home/pashdown/insteon-mqtt/venv/lib/python3.6/site-packages/insteon_mqtt/Modem.py", line 619, in scene
    assert 0x01 <= group <= 0xff
AssertionError
```

**Comment by TD22057** [comment]
Please dump your IO link database.  Your modem has a scene linking the modem to the IOlink using group 0 which is incorrect.  The IO link is finding that and thinking that it's the virtual scene that it wants when it isn't.  If you delete that entry, it should be OK.  I can change the code to check for invalid groups in the scene but it shouldn't be there in the first place.

**Comment by pashdown** [comment]
Factory erased my PLM, reset my MQTT database.  Re-joined and re-paired the water main iolinc.  This is what I get when I hit the switch.  Nothing actually happens at the iolinc.
```
Jan 22 07:52:58 cosine insteon-mqtt[6655]: 2020-01-22 07:52:58 DEBUG IOLinc: IOLinc message insteon/39.4d.6e/scene b'ON'
Jan 22 07:52:58 cosine insteon-mqtt[6655]: 2020-01-22 07:52:58 DEBUG MsgTemplate: Input template render: '{ "cmd" : "on" }'
Jan 22 07:52:58 cosine insteon-mqtt[6655]: 2020-01-22 07:52:58 INFO IOLinc: IOLinc input command: {'cmd': 'on'}
Jan 22 07:52:58 cosine insteon-mqtt[6655]: 2020-01-22 07:52:58 INFO IOLinc: IOLinc 39.4d.6e (water main) triggering modem scene 38
Jan 22 07:52:58 cosine insteon-mqtt[6655]: 2020-01-22 07:52:58 INFO Modem: Modem scene 38 on=on
Jan 22 07:52:58 cosine insteon-mqtt[6655]: 2020-01-22 07:52:58 INFO Protocol: Write message to modem: Modem Scene: grp: 38 cmd: 0x11 0x00
Jan 22 07:52:58 cosine insteon-mqtt[6655]: 2020-01-22 07:52:58 DEBUG Protocol: Write bytes to modem: b'\x02a&\x11\x00'
Jan 22 07:52:58 cosine insteon-mqtt[6655]: 2020-01-22 07:52:58 DEBUG Serial: Wrote 5 bytes to serial /dev/insteon
Jan 22 07:52:58 cosine insteon-mqtt[6655]: 2020-01-22 07:52:58 INFO Protocol: Read 0x61: Modem Scene: grp: 38 cmd: 0x11 0x00 ack: False
Jan 22 07:52:58 cosine insteon-mqtt[6655]: 2020-01-22 07:52:58 DEBUG Protocol: Passing msg to write handler: ModemScene handler
Jan 22 07:52:58 cosine insteon-mqtt[6655]: 2020-01-22 07:52:58 DEBUG Protocol: Write handler finished
```

**Comment by pashdown** [comment]
Also, if it would help, I'm switching from a ISY-994a.  I can hook it back up and dump its PLM interactions if that would help you deal with IOLincs better. It handled them flawlessly.

**Comment by pashdown** [comment]
Here are two logs from the ISY.  First is the log from the water valve (39.48.E6), which is first shut close by sending an "on" command and then reopened by sending an "off" command.

[water.txt](https://github.com/TD22057/insteon-mqtt/files/4100841/water.txt)

Here is the garage (34.89.7A), which is opened with an "on" and then closed, also with an "on".

[garage.txt](https://github.com/TD22057/insteon-mqtt/files/4100844/garage.txt)

As a bonus, here's the linking process for the Water, which is an IOLinc 2450 (refurb).  The ISY differentiates every different device when linking.  [water-link.txt](https://github.com/TD22057/insteon-mqtt/files/4100994/water-link.txt)

I may be able to send you an ISY if that would help you debug device protocols.

Also, you'll note the Insteon IDs have changed.  That is because I was masking them before.  Now, I don't GAF.  I'd just like to help fix this if I can.

**Comment by pashdown** [comment]
I've switched to the HACS ISY994 integration, which works well.  So you can close this if you want.

**Comment by philletourneau** [comment]
I'm also having issues with my IOLinc's that seem kinda similar to this.

**Comment by krkeegan** [comment]
#197 has been merged into dev and will be pushed to master next week.  I think this will solve your issues.
