### ISSUE TITLE
Dimmer message error

### ISSUE THREAD

**Issue by pmgendron** [TD22057/insteon-mqtt#209]
Hi,

I have several dimmers in my db and all are working well, except 1, and this is the error I'm getting when starting insteon-mqtt:

```
2020-04-21 01:48:12 INFO Dimmer: Dimmer message insteon/2b.59.73/level b'OFF'

2020-04-21 01:48:12 ERROR MsgTemplate: Error rendering template '{ "cmd" : 
"{{json.state.lower()}}",

  "level" : {% if json.brightness is defined %}

               {{json.brightness}}

            {% else %}

               255

            {% endif %} }

' with data: {'value': 'OFF', 'json': None}

Traceback (most recent call last):

  File "/opt/insteon-mqtt/lib/python3.7/site-packages/insteon_mqtt/mqtt/MsgTemplate.py", line 200, in _render

    return template.render(data)

  File "/opt/insteon-mqtt/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()

  File "/opt/insteon-mqtt/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception

    reraise(*rewrite_traceback_stack(source=source))

  File "/opt/insteon-mqtt/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)

  File "<template>", line 1, in top-level template code

  File "/opt/insteon-mqtt/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)

jinja2.exceptions.UndefinedError: 'None' has no attribute 'state'

2020-04-21 01:48:12 DEBUG MsgTemplate: Input template render: 'None'

2020-04-21 01:48:12 INFO Dimmer: Dimmer input command: None

2020-04-21 01:48:12 ERROR Dimmer: Invalid dimmer command: None

Traceback (most recent call last):

  File "/opt/insteon-mqtt/lib/python3.7/site-packages/insteon_mqtt/mqtt/Dimmer.py", line 259, in _input_set_level

    is_on, mode = util.parse_on_off(data)  File "/opt/insteon-mqtt/lib/python3.7/site-packages/insteon_mqtt/mqtt/util.py", line 30, in parse_on_off
    cmd = data.get('cmd').lower()

AttributeError: 'NoneType' object has no attribute 'get'
```

I tried joining the dimmer once more, but I get the following error:
`ERROR: Serial read error from /dev/insteon`

I can control the defaulting device from the command line even with this error, but I'd like to fix it if possible.

any help would be appreciated!

thanks in advance!

pm

**Comment by TD22057** [comment]
Look at the config.yaml comments around 'level_topic'.  Sending a message with level support requires that the message be in JSON format.  You sent a message `OFF` to the level topic but your config input for that payload doesn't understand how to parse that - it has to be valid json.  If you're using home assistant, then you need to set `schema: json` as the docs for dimmers show.

**Comment by krkeegan** [comment]
I am going to close this as a configuration error.  Feel free to re-open if you are still having issues.
