### ISSUE TITLE
Keypadlinc not turning on/off, with errors

### ISSUE THREAD

**Issue by MrGibbage** [TD22057/insteon-mqtt#373]
Ver 0.7.4. When I try to turn my family room KPL on with MQTT, I get an error:

````
2021-03-30 15:52:26 INFO KeypadLinc: KeypadLinc message insteon/4c.f9.cb/set/1 b'{"cmd": "on"}'
2021-03-30 15:52:26 ERROR MsgTemplate: Invalid JSON message { "cmd" : "{"cmd": "on"}" } from template { "cmd" : "{{value.lower()}}" }
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/insteon_mqtt/mqtt/MsgTemplate.py", line 177, in to_json
    return json.loads(value)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 14 (char 13)
2021-03-30 15:52:26 ERROR KeypadLinc: Invalid input command did match a dimmer or on/off message: b'{"cmd": "on"}'
````
I get this with MQTT explorer, or through Lovelace UI, if that matters.

Also, I couldn't tell if the level : LEVEL was required or not, but I did try that too:

````
2021-03-30 15:55:06 INFO KeypadLinc: KeypadLinc message insteon/4c.f9.cb/set/1 b'{"cmd": "on", "level" : 255}'
2021-03-30 15:55:06 ERROR MsgTemplate: Invalid JSON message { "cmd" : "{"cmd": "on", "level" : 255}" } from template { "cmd" : "{{value.lower()}}" }
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/insteon_mqtt/mqtt/MsgTemplate.py", line 177, in to_json
    return json.loads(value)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 14 (char 13)
2021-03-30 15:55:06 ERROR KeypadLinc: Invalid input command did match a dimmer or on/off message: b'{"cmd": "on", "level" : 255}'
````

Here's my KPL template (pretty sure it is stock, but I did try messing around with it once, some time ago. Maybe I broke it then...)

````
  keypad_linc:
    btn_state_topic: 'insteon/{{address}}/state/{{button}}'
    btn_state_payload: '{{on_str.upper()}}'

    dimmer_state_topic: 'insteon/{{address}}/state/1'
    dimmer_state_payload: >
       { "state" : "{{on_str.upper()}}", "brightness" : {{level_255}} }

    btn_on_off_topic: 'insteon/{{address}}/set/{{button}}'

    # this seems to be the line causing the trouble???
    btn_on_off_payload: '{ "cmd" : "{{value.lower()}}" }'

    dimmer_level_topic: 'insteon/{{address}}/set/1'

    dimmer_level_payload: >
       { "cmd" : "{{json.state.lower()}}"
         {% if json.brightness is defined %}
             , "level" : {{json.brightness}}
         {% endif %}
         {% if json.transition is defined %}
             , "transition" : {{json.transition}}
         {% endif %} }

    btn_scene_topic: 'insteon/{{address}}/scene/{{button}}'
    btn_scene_payload: '{ "cmd" : "{{json.cmd.lower()}}"
                          {% if json.brightness is defined %}
                              , "level" : {{json.brightness}}
                          {% endif %}
                        }'

````

**Comment by krkeegan** [comment]
You are sending the wrong payload, you are sending `{ "cmd" : "{"cmd": "on"}" }` it should be `{ "cmd" : "on" }`

**Comment by MrGibbage** [comment]
Thanks!

Do you know how I would then make the switch work in Lovelace? Strangely, turning the switch off works, but turning it on does not.

````
2021-03-30 16:56:09 INFO KeypadLinc: KeypadLinc message insteon/4c.f9.cb/set/1 b'{"state": "OFF"}'
2021-03-30 16:56:09 INFO KeypadLinc: KeypadLinc message insteon/4c.f9.cb/set/1 b'{"state": "OFF"}'
2021-03-30 16:56:09 DEBUG MsgTemplate: Input template render: '{ "cmd" : "off"
  
   }'
2021-03-30 16:56:09 INFO KeypadLinc: KeypadLinc input command: {'cmd': 'off'}
2021-03-30 16:56:09 INFO KeypadLinc: KeypadLinc 4c.f9.cb cmd: off grp 0
2021-03-30 16:56:09 DEBUG MsgHistory: Average hops 0.7, using 1
2021-03-30 16:56:09 INFO Protocol: Write message to modem: Std: 4c.f9.cb, Type.DIRECT, 13 00 
2021-03-30 16:56:09 DEBUG Protocol: Write bytes to modem: 02624cf9cb051300
2021-03-30 16:56:09 DEBUG Serial: Wrote 8 bytes to serial /dev/ttyUSB0
2021-03-30 16:56:09 INFO Protocol: Read 0x62: Std: 4c.f9.cb, Type.DIRECT, 13 00 ack: True
2021-03-30 16:56:09 DEBUG Protocol: Passing msg to write handler: StandardCmd handler
2021-03-30 16:56:09 DEBUG StandardCmd: 4c.f9.cb got msg ACK
2021-03-30 16:56:09 INFO Protocol: Read 0x50: Std: 4c.f9.cb->53.c1.0e Type.DIRECT_ACK cmd: 13 00
2021-03-30 16:56:09 DEBUG Protocol: Setting next write time: 1617137769.479264
2021-03-30 16:56:09 DEBUG MsgHistory: Received 0 hops, total 2 for 4 entries
2021-03-30 16:56:09 DEBUG Protocol: Passing msg to write handler: StandardCmd handler
2021-03-30 16:56:09 DEBUG KeypadLinc: KeypadLinc 4c.f9.cb ACK: Std: 4c.f9.cb->53.c1.0e Type.DIRECT_ACK cmd: 13 00
2021-03-30 16:56:09 INFO KeypadLinc: Setting device 4c.f9.cb (family room kpl) grp=1 on=0 normal
2021-03-30 16:56:09 INFO KeypadLinc: MQTT received button press 4c.f9.cb (family room kpl) = btn 1 at 0 normal 
2021-03-30 16:56:09 DEBUG Mqtt: MQTT publish insteon/4c.f9.cb/state/1 { "state" : "OFF", "brightness" : 0 } qos=1 ret=1
2021-03-30 16:56:09 DEBUG Protocol: Write handler finished
2021-03-30 16:56:09 DEBUG Mqtt: MQTT writing
2021-03-30 16:56:41 INFO KeypadLinc: KeypadLinc message insteon/4c.f9.cb/set/1 b'{"state": "ON"}'
2021-03-30 16:56:41 INFO KeypadLinc: KeypadLinc message insteon/4c.f9.cb/set/1 b'{"state": "ON"}'
2021-03-30 16:56:41 DEBUG MsgTemplate: Input template render: '{ "cmd" : "on"
  
   }'
2021-03-30 16:56:41 INFO KeypadLinc: KeypadLinc input command: {'cmd': 'on'}
2021-03-30 16:56:41 ERROR KeypadLinc: Invalid KeypadLinc level command: {'cmd': 'on'}
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/insteon_mqtt/mqtt/KeypadLinc.py", line 330, in _input_set_level
    level = 0 if not is_on else int(data.get('level'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-03-30 16:56:41 ERROR MsgTemplate: Invalid JSON message { "cmd" : "{"state": "on"}" } from template { "cmd" : "{{value.lower()}}" }
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/insteon_mqtt/mqtt/MsgTemplate.py", line 177, in to_json
    return json.loads(value)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 14 (char 13)
2021-03-30 16:56:41 ERROR KeypadLinc: Invalid input command did match a dimmer or on/off message: b'{"state": "ON"}'
````

It seems that using the Lovelace UI, it always sends { "cmd" : "on (or off)" }. I think I need to tell HA/Lovelace that this device needs to send ON or OFF as required???

**Comment by krkeegan** [comment]
You should check the HA documents such as https://www.home-assistant.io/integrations/light.mqtt/ maybe something like command_on_template or something.
