### ISSUE TITLE
can't send messages to FanLinc group 2

### ISSUE THREAD

**Issue by lnr0626** [TD22057/insteon-mqtt#398]
**Describe the bug**
An exception is thrown when attempting to send a message to my FanLinc for group 2

**To Reproduce**
For context, I'm using the hassio add-on installation on the latest version (`0.9.0`)

1. have a fanlinc joined/paired with the modem
2. Open the Web UI
3. execute the following command:
```
>>>insteon-mqtt config.yaml on -g 2 master-fan
```
6. See error:
```
Commanding fan_linc device 47.6b.d0 (master-fan) cmd=on
ERROR: Error running command on on device 47.6b.d0 (master-fan)
```

**Expected behavior**
I expected the fan to have turned on and something similar to the following output:
```
Commanding fan_linc device 47.6b.d0 (master-fan) cmd=on
Device state updated to on=True
```

**Log Output**
Please change your logging level to 10 by editing Logging.level in your config.yaml file.

```txt
# Put your relevant logging output below this line
2021-05-13 22:48:55.715 DEBUG Mqtt: Received PUBLISH (d0, q1, r0, m256), 'insteon/command/master-fan', ...  (78 bytes)
2021-05-13 22:48:55.715 DEBUG Mqtt: Sending PUBACK (Mid: 256)
2021-05-13 22:48:55.715 INFO Mqtt: MQTT message insteon/command/master-fan b'{"cmd": "on", "level": 255, "group": 2, "reason": "", "session": "3218423953"}'
2021-05-13 22:48:55.715 UI Mqtt: Commanding fan_linc device 47.6b.d0 (master-fan) cmd=on
2021-05-13 22:48:55.715 DEBUG Mqtt: Sending PUBLISH (d0, q0, r0, m55), 'b'insteon/command/master-fan/session/3218423953'', ... (86 bytes)
2021-05-13 22:48:55.715 DEBUG Mqtt: MQTT publish insteon/command/master-fan/session/3218423953 {"type": "MESSAGE", "data": "Commanding fan_linc device 47.6b.d0 (master-fan) cmd=on"} qos=0 ret=False
2021-05-13 22:48:55.715 INFO ResponderBase: Device 47.6b.d0 grp: 2 cmd: on normal
2021-05-13 22:48:55.715 ERROR Mqtt: Error running command on on device 47.6b.d0 (master-fan)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/insteon_mqtt/mqtt/Mqtt.py", line 326, in handle_cmd
    cmd_func(on_done=on_done, **data)
  File "/usr/lib/python3.8/site-packages/insteon_mqtt/device/base/ResponderBase.py", line 115, in on
    assert group in self.responder_groups
AssertionError
2021-05-13 22:48:55.716 DEBUG Mqtt: Sending PUBLISH (d0, q0, r0, m56), 'b'insteon/command/master-fan/session/3218423953'', ... (85 bytes)
2021-05-13 22:48:55.716 DEBUG Mqtt: MQTT publish insteon/command/master-fan/session/3218423953 {"type": "ERROR", "data": "Error running command on on device 47.6b.d0 (master-fan)"} qos=0 ret=False
2021-05-13 22:48:55.716 DEBUG Mqtt: Sending PUBLISH (d0, q0, r0, m57), 'b'insteon/command/master-fan/session/3218423953'', ... (29 bytes)
2021-05-13 22:48:55.716 DEBUG Mqtt: MQTT publish insteon/command/master-fan/session/3218423953 {"type": "END", "data": null} qos=0 ret=False
2021-05-13 22:48:55.716 DEBUG Mqtt: MQTT writing
```

**Your Configuration**
What are the relevant entries in your config.yaml?  Please include the device definition of the device affected.
```yaml
# Put your relevant config.yaml text below this line
    # FanLinc fan controller (dimmer+fan).
    fan_linc:
      - 47.6b.d0: master-fan
```

Happy to include more of the config if needed, just lmk what you want to see

**Hardware Details**
- What OS is Insteon-MQTT runnning on?
Hassio running on an x86 NUC

- The model of your Modem, see https://github.com/TD22057/insteon-mqtt/blob/master/docs/mqtt.md#get-device-model-information
```txt
# Please paste the output of get-model for the modem below this line
Commanding Modem device 50.04.ca (modem) cmd=get_model
Modem 50.04.ca model information: NETWORK_BRIDGES (0x03): '2413U' (0x15) 'PowerLinc USB Modem (Dual Band)'
Success get_model
```

- The model of the affected Device, see https://github.com/TD22057/insteon-mqtt/blob/master/docs/mqtt.md#get-device-model-information
```txt
# Please paste the output of get-model for the affected device below this line
Commanding fan_linc device 47.6b.d0 (master-fan) cmd=get_model
Device 47.6b.d0 received model information: DIMMABLE_LIGHTING (0x01): '2475F' (0x2e) 'FanLinc' firmware: 0x45
Operation complete
```

**Additional context**

If you need any other info, please let met know. I'm also more than willing to help debug/fix whatever it is if this is actually a bug and not just user error :-)

**Comment by lnr0626** [comment]
fwiw i was able to work around this using a few scenes, leaving this open as i'm unsure if this is a bug or not
