### ISSUE TITLE
Keypad with new dimmer/switch in dev branch does not work

### ISSUE THREAD

**Issue by djfjeff** [TD22057/insteon-mqtt#61]
It seems the new keypad code in the dev branch does not work. I have a dimmer keypad, updated the config.yaml file and HASS configuration and when I try to turn the button 1 on (so the load that is connected to the keypad), all I get is :

2018-04-03 07:57:58 INFO KeypadLinc: KeypadLinc btn 1 message insteon/42.16.xx/set/1 b'{"state": "ON"}'   
2018-04-03 07:57:58 DEBUG MsgTemplate: Input template render: '{ "cmd" : "{"state": "on"}" }'             
2018-04-03 07:57:58 ERROR MsgTemplate: Invalid JSON message { "cmd" : "{"state": "on"}" } from template { "cmd" : "{{value.lower()}}" }                                                                              
Traceback (most recent call last):                   
  File "/opt/DEV2-insteon-mqtt/DEV2-insteon-mqtt-venv/lib64/python3.6/site-packages/insteon_mqtt/mqtt/MsgTemplate.py", line 162, in to_json                                                                          
    return json.loads(value)                         
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads                                        
    return _default_decoder.decode(s)                
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode                                        
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                     
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode                                    
    obj, end = self.scan_once(s, idx)                
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 14 (char 13)

**Comment by TD22057** [comment]
Thanks - I forget that the HASS dimmer sends both set and level topics so what I did isn't going to work because the non-dimmer isn't a JSON light.   I'll rethink this tonight and figure out what to do.

**Comment by TD22057** [comment]
@j3kestrel 
OK - I think it's fixed.  I had to change the internals so that when it's a dimmer, the on/off and level topics can be the same (like insteon/aa.bb.cc/set/1) and it will try the level template first, then the on/off template.  This way either command style works fine for the dimmer btn 1.  I ran tests with my keypadlinc defined as a dimmer and a switch in both systems and I think it's now working.

Please give it a try.  Take a look at the updated config.yaml - it has more instructions for the keypadlinc now.  If it's working for you, we can close this out.

**Comment by djfjeff** [comment]
Tested and works fine here for the dimmer keypadlinc! I will close this issue as it seems it's resolved, thanks!
